<a href="https://colab.research.google.com/github/sanjanasrinivas22/6thSem-ML-Lab/blob/main/1BM23CS301_Lab_6_Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

data = pd.read_csv("iris.csv")

X = data.drop("species", axis=1)
y = data["species"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9666666666666667
Confusion Matrix:
[[ 7  0  0]
 [ 0 17  0]
 [ 0  1  5]]


In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix

data = pd.read_csv("drug.csv")

le = LabelEncoder()

for column in data.columns:
    if data[column].dtype == object:
        data[column] = le.fit_transform(data[column])

X = data.drop("Drug", axis=1)
y = data["Drug"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.975
Confusion Matrix:
[[ 3  0  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0  3  0  0]
 [ 0  0  0 11  1]
 [ 0  0  0  0 17]]


In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

data = pd.read_csv("petrol_consumption.csv")

X = data.drop("Petrol_Consumption", axis=1)
y = data["Petrol_Consumption"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = DecisionTreeRegressor()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)

Mean Absolute Error: 57.1
Mean Squared Error: 7309.1
Root Mean Squared Error: 85.49327458929153


In [7]:
import pandas as pd
import math
from collections import Counter

data = pd.read_csv("iris.csv")

def entropy(labels):
    counts = Counter(labels)
    total = len(labels)
    ent = 0
    for c in counts.values():
        p = c/total
        ent -= p * math.log2(p)
    return ent

def information_gain(data, feature, target):
    total_entropy = entropy(data[target])
    values = data[feature].unique()
    weighted_entropy = 0

    for v in values:
        subset = data[data[feature] == v]
        weighted_entropy += (len(subset)/len(data)) * entropy(subset[target])

    return total_entropy - weighted_entropy

def best_feature(data, features, target):
    gains = []
    for f in features:
        gains.append(information_gain(data, f, target))
    return features[gains.index(max(gains))]

def build_tree(data, features, target):
    labels = data[target]

    if len(set(labels)) == 1:
        return labels.iloc[0]

    if len(features) == 0:
        return Counter(labels).most_common(1)[0][0]

    best = best_feature(data, features, target)
    tree = {best:{}}

    for value in data[best].unique():
        subset = data[data[best] == value]
        new_features = [f for f in features if f != best]
        tree[best][value] = build_tree(subset, new_features, target)

    return tree

features = list(data.columns[:-1])
target = "species"

tree = build_tree(data, features, target)

print("Decision Tree:")
print(tree)

Decision Tree:
{'petal_length': {np.float64(1.4): 'Iris-setosa', np.float64(1.3): 'Iris-setosa', np.float64(1.5): 'Iris-setosa', np.float64(1.7): 'Iris-setosa', np.float64(1.6): 'Iris-setosa', np.float64(1.1): 'Iris-setosa', np.float64(1.2): 'Iris-setosa', np.float64(1.0): 'Iris-setosa', np.float64(1.9): 'Iris-setosa', np.float64(4.7): 'Iris-versicolor', np.float64(4.5): {'sepal_length': {np.float64(6.4): 'Iris-versicolor', np.float64(5.7): 'Iris-versicolor', np.float64(5.6): 'Iris-versicolor', np.float64(6.2): 'Iris-versicolor', np.float64(6.0): 'Iris-versicolor', np.float64(5.4): 'Iris-versicolor', np.float64(4.9): 'Iris-virginica'}}, np.float64(4.9): {'sepal_width': {np.float64(3.1): 'Iris-versicolor', np.float64(2.5): 'Iris-versicolor', np.float64(2.8): 'Iris-virginica', np.float64(2.7): 'Iris-virginica', np.float64(3.0): 'Iris-virginica'}}, np.float64(4.0): 'Iris-versicolor', np.float64(4.6): 'Iris-versicolor', np.float64(3.3): 'Iris-versicolor', np.float64(3.9): 'Iris-versicolor'

In [8]:
import pandas as pd
import math
from collections import Counter

data = pd.read_csv("drug.csv")

for column in data.columns:
    if data[column].dtype == object:
        data[column] = data[column].astype("category").cat.codes

def entropy(labels):
    counts = Counter(labels)
    total = len(labels)
    ent = 0
    for c in counts.values():
        p = c/total
        ent -= p * math.log2(p)
    return ent

def information_gain(data, feature, target):
    total_entropy = entropy(data[target])
    values = data[feature].unique()
    weighted_entropy = 0

    for v in values:
        subset = data[data[feature] == v]
        weighted_entropy += (len(subset)/len(data)) * entropy(subset[target])

    return total_entropy - weighted_entropy

def best_feature(data, features, target):
    gains = []
    for f in features:
        gains.append(information_gain(data, f, target))
    return features[gains.index(max(gains))]

def build_tree(data, features, target):
    labels = data[target]

    if len(set(labels)) == 1:
        return labels.iloc[0]

    if len(features) == 0:
        return Counter(labels).most_common(1)[0][0]

    best = best_feature(data, features, target)
    tree = {best:{}}

    for value in data[best].unique():
        subset = data[data[best] == value]
        new_features = [f for f in features if f != best]
        tree[best][value] = build_tree(subset, new_features, target)

    return tree

features = list(data.columns[:-1])
target = "Drug"

tree = build_tree(data, features, target)

print("Decision Tree:")
print(tree)

Decision Tree:
{'Na_to_K': {np.float64(25.355): np.int8(4), np.float64(13.093): np.int8(2), np.float64(10.114): np.int8(2), np.float64(7.798): np.int8(3), np.float64(18.043): np.int8(4), np.float64(8.607): np.int8(3), np.float64(16.275): np.int8(4), np.float64(11.037): np.int8(2), np.float64(15.171): np.int8(4), np.float64(19.368): np.int8(4), np.float64(11.767): np.int8(2), np.float64(19.199): np.int8(4), np.float64(15.376): np.int8(4), np.float64(20.942): np.int8(4), np.float64(12.703): np.int8(3), np.float64(15.516): np.int8(4), np.float64(11.455): np.int8(3), np.float64(13.972): np.int8(0), np.float64(7.298): np.int8(2), np.float64(25.974): np.int8(4), np.float64(19.128): np.int8(4), np.float64(25.917): np.int8(4), np.float64(30.568): np.int8(4), np.float64(15.036): np.int8(4), np.float64(33.486): np.int8(4), np.float64(18.809): np.int8(4), np.float64(30.366): np.int8(4), np.float64(9.381): np.int8(3), np.float64(22.697): np.int8(4), np.float64(17.951): np.int8(4), np.float64(8.75)

In [10]:
import pandas as pd
import numpy as np

data = pd.read_csv("petrol_consumption.csv")

X = data.drop("Petrol_Consumption", axis=1).values
y = data["Petrol_Consumption"].values

split = int(0.8 * len(X))

X_train = X[:split]
X_test = X[split:]
y_train = y[:split]
y_test = y[split:]

prediction = np.mean(y_train)

y_pred = [prediction] * len(y_test)

mae = np.mean(np.abs(y_test - y_pred))
mse = np.mean((y_test - y_pred) ** 2)
rmse = np.sqrt(mse)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)

Mean Absolute Error: 114.60526315789475
Mean Squared Error: 26343.830193905822
Root Mean Squared Error: 162.30782542411757
